pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t python-demo .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run --rm python-demo'
            }
        }
    }
}
